### ISSUE TITLE
Can we have access to the source code please?

### ISSUE THREAD

**Issue by 03hgryan** [raj074/mern-social-media#2]
This is a great repository!

**Comment by raj074** [comment]
check main branch

**Comment by 03hgryan** [comment]
Amazing thanks!! But it doesn't seem like messaging parts are not pushed yet 😅🙏

**Comment by raj074** [comment]
> Amazing thanks!! But it doesn't seem like messaging parts are not pushed yet 😅🙏

It is complted.  I'll push updates soon
