### ISSUE TITLE
Hi, sorry this is me again sorry to bother you :)

### ISSUE THREAD

**Issue by 03hgryan** [raj074/mern-social-media#5]
I am trying to deploy it via heroku as you did... and I think I am getting error doing it since my script in package.json is problematic. It is "heroku-postbuild": "cd client && npm install && npm install --only=dev --no-shrinkwrap && npm run build"
Can you please help me with this 😅 Or is there something else I should do to successfully deply on heroku..??

**Comment by raj074** [comment]
there are my scripts:
"scripts": {
    "start": "node server.js",
    "server": "nodemon server.js",
    "client": "cd client && npm run start",
    "client-install": "cd client && npm install",
    "server-install": "npm install",
    "install-all": "concurrently \"npm run client-install\" \"npm run server-install\" ",
    "dev": "concurrently \"npm run client\" \"npm run server\" ",
    "heroku-postbuild": "cd client && npm install && npm run build"
  },

**Comment by 03hgryan** [comment]
I actually added this 

"heroku-postbuild": "NPM_CONFIG_PRODUCTION=false && npm install --prefix client && npm run build --prefix client"

in script and added 

if (process.env.NODE_ENV === "production") {
  // set static folder
  app.use(express.static("client/build"));
  app.get("*", (req, res) => {
    res.sendFile(path.resolve(__dirname, "client", "build", "index.html"));
  });
} 

in server.js and it worked :)
Thanks anyway for the quick reply you are amazing !!
